import './globals.css'
import { Inter } from 'next/font/google'
import { LanguageProvider } from './LanguageContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mridakriti',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}) {

  return (
    <html lang='en'>
      <LanguageProvider>
        <body className={inter.className}>
          {children}
        </body>
      </LanguageProvider>
    </html>
  )
}
